function [] = vectors_2d_3d(data, T, force_LCS, moment_LCS,...
                                                        output_dir_plots)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%       Ploting the vectors of FORCES versus location in 2d and 3d        %
%        (reaction force, forces at the ankle knee and hip joint)         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for pat = 1 %: length(data(:, 1))       % Patients = 1
    for cur_trial = 1 %: trial(1, pat)  % Walking trials = [2]
        figure(12)
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3
            subplot(2, 2, 1)
            quiver3(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(2),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(force_LCS{pat, cur_trial}(i).ankle),...
                force_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(force_LCS{pat, cur_trial}(i).ankle),...
                force_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(force_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver3(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(2),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).knee(1) /...
                norm(force_LCS{pat, cur_trial}(i).knee),...
                force_LCS{pat, cur_trial}(i).knee(2) /...
                norm(force_LCS{pat, cur_trial}(i).knee),...
                force_LCS{pat, cur_trial}(i).knee(3) /...
                norm(force_LCS{pat, cur_trial}(i).knee), 'g')
            quiver3(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(2),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).hip(1) /...
                norm(force_LCS{pat, cur_trial}(i).hip),...
                force_LCS{pat, cur_trial}(i).hip(2) /...
                norm(force_LCS{pat, cur_trial}(i).hip),...
                force_LCS{pat, cur_trial}(i).hip(3) /...
                norm(force_LCS{pat, cur_trial}(i).hip), 'b')
        end
        title(['Patient ' num2str(pat) ' Reaction Forces'])
        xlabel('Anterior-Posterior')
        ylabel('Medial-Lateral')
        zlabel('Superior-Inferior ')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3
            subplot(2, 2, 2)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(2),...
                force_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(force_LCS{pat, cur_trial}(i).ankle),...
                force_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(force_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(2),...
                force_LCS{pat, cur_trial}(i).knee(1) /...
                norm(force_LCS{pat, cur_trial}(i).knee),...
                force_LCS{pat, cur_trial}(i).knee(2) /...
                norm(force_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(2),...
                force_LCS{pat, cur_trial}(i).hip(1) /...
                norm(force_LCS{pat, cur_trial}(i).hip),...
                force_LCS{pat, cur_trial}(i).hip(2) /...
                norm(force_LCS{pat, cur_trial}(i).hip), 'b')
        end
        xlabel('Anterior-Posterior')
        ylabel('Medial-Lateral')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3    
            subplot(2, 2, 3)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(2),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(force_LCS{pat, cur_trial}(i).ankle),...
                force_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(force_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(2),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).knee(2) /...
                norm(force_LCS{pat, cur_trial}(i).knee),...
                force_LCS{pat, cur_trial}(i).knee(3) /...
                norm(force_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(2),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).hip(2) /...
                norm(force_LCS{pat, cur_trial}(i).hip),...
                force_LCS{pat, cur_trial}(i).hip(3) /...
                norm(force_LCS{pat, cur_trial}(i).hip), 'b')
        end
        xlabel('Medial-Lateral')
        ylabel('Superior-Inferior ')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3
            subplot(2, 2, 4)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(force_LCS{pat, cur_trial}(i).ankle),...
                force_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(force_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).knee(1) /...
                norm(force_LCS{pat, cur_trial}(i).knee),...
                force_LCS{pat, cur_trial}(i).knee(3) /...
                norm(force_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                force_LCS{pat, cur_trial}(i).hip(1) /...
                norm(force_LCS{pat, cur_trial}(i).hip),...
                force_LCS{pat, cur_trial}(i).hip(3) /...
                norm(force_LCS{pat, cur_trial}(i).hip), 'b')
        end
        legend({'Ankle Force' 'Knee Force' 'Hip Force'}, 'Location',...
                                                         'southeast')
        xlabel('Anterior-Posterior')
        ylabel('Superior-Inferior ')
    end
end
set(gcf, 'Units', 'normalized', 'Position', [0, 0, .99, .88])
hold off


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%       Ploting the vectors of MOMENTS versus location in 2d and 3d       %
%        (reaction moment, moment at the ankle, knee and hip joint)       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for pat = 1 %: length(data(:, 1))       % Patients = 1
    for cur_trial = 1 %: trial(1, pat)  % Walking trials = [2]
        figure(13)
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3
                                    
            subplot(2, 2, 1)
            quiver3(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(2),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle),...
                moment_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle),...
                moment_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver3(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(2),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).knee(1) /...
                norm(moment_LCS{pat, cur_trial}(i).knee),...
                moment_LCS{pat, cur_trial}(i).knee(2) /...
                norm(moment_LCS{pat, cur_trial}(i).knee),...
                moment_LCS{pat, cur_trial}(i).knee(3) /...
                norm(moment_LCS{pat, cur_trial}(i).knee), 'g')
            quiver3(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(2),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).hip(1) /...
                norm(moment_LCS{pat, cur_trial}(i).hip),...
                moment_LCS{pat, cur_trial}(i).hip(2) /...
                norm(moment_LCS{pat, cur_trial}(i).hip),...
                moment_LCS{pat, cur_trial}(i).hip(3) /...
                norm(moment_LCS{pat, cur_trial}(i).hip), 'b')
        end
        title(['Patient ' num2str(pat) ' Reaction Moments'])
        xlabel('Anterior-Posterior')
        ylabel('Medial-Lateral')
        zlabel('Superior-Inferior ')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3
            
            subplot(2, 2, 2)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(2),...
                moment_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle),...
                moment_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(2),...
                moment_LCS{pat, cur_trial}(i).knee(1) /...
                norm(moment_LCS{pat, cur_trial}(i).knee),...
                moment_LCS{pat, cur_trial}(i).knee(2) /...
                norm(moment_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(2),...
                moment_LCS{pat, cur_trial}(i).hip(1) /...
                norm(moment_LCS{pat, cur_trial}(i).hip),...
                moment_LCS{pat, cur_trial}(i).hip(2) /...
                norm(moment_LCS{pat, cur_trial}(i).hip), 'b')
        end
        title(['Patient ' num2str(pat) ' Reaction Moments'])
        xlabel('Anterior-Posterior')
        ylabel('Medial-Lateral')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3

            subplot(2, 2, 3)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(2),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).ankle(2) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle),...
                moment_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(2),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).knee(2) /...
                norm(moment_LCS{pat, cur_trial}(i).knee),...
                moment_LCS{pat, cur_trial}(i).knee(3) /...
                norm(moment_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(2),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).hip(2) /...
                norm(moment_LCS{pat, cur_trial}(i).hip),...
                moment_LCS{pat, cur_trial}(i).hip(3) /...
                norm(moment_LCS{pat, cur_trial}(i).hip), 'b')
        end
        title(['Patient ' num2str(pat) ' Reaction Moments'])
        xlabel('Medial-Lateral')
        ylabel('Superior-Inferior ')
        for i = 1 : 3 : length(data{1, 1}) % Time discretizations = 201/3

            subplot(2, 2, 4)
            quiver(T{pat, cur_trial}(i, 1).LCS.origin(1),...
                T{pat, cur_trial}(i, 1).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).ankle(1) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle),...
                moment_LCS{pat, cur_trial}(i).ankle(3) /...
                norm(moment_LCS{pat, cur_trial}(i).ankle), 'r')
            hold on
            quiver(T{pat, cur_trial}(i, 2).LCS.origin(1),...
                T{pat, cur_trial}(i, 2).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).knee(1) /...
                norm(moment_LCS{pat, cur_trial}(i).knee),...
                moment_LCS{pat, cur_trial}(i).knee(3) /...
                norm(moment_LCS{pat, cur_trial}(i).knee), 'g')
            quiver(T{pat, cur_trial}(i, 3).LCS.origin(1),...
                T{pat, cur_trial}(i, 3).LCS.origin(3),...
                moment_LCS{pat, cur_trial}(i).hip(1) /...
                norm(moment_LCS{pat, cur_trial}(i).hip),...
                moment_LCS{pat, cur_trial}(i).hip(3) /...
                norm(moment_LCS{pat, cur_trial}(i).hip), 'b')
        end
        title(['Patient ' num2str(pat) ' Reaction Moments'])
        legend({'Ankle Moment' 'Knee Moment' 'Hip Moment'})
        xlabel('Anterior-Posterior')
        ylabel('Superior-Inferior ')
    end
end
set(gcf, 'Units', 'normalized', 'Position', [0, 0, .99, .88])
hold off

for i = 12 : 13
    saveas(figure(i), [output_dir_plots 'Figure_' num2str(i) '.png']);
end
end